name: animated_qr
description: "An app for sending and receiving files via animated QR codes"
publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  rs:
    path: rust_builder
  flutter_rust_bridge: 2.11.1

  file_picker: ^10.3.2
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  flutter_form_builder: ^10.2.0
  go_router: ^16.2.0
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  shared_preferences: ^2.5.3
  form_builder_validators: ^11.2.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.0
  mobx_codegen: ^2.7.2

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - misc/icon.png
